name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  - name: Run application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: ./gradlew run
    