name: CI
on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.9
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
